version: '3.4'

services:
  db:
    container_name: db
    build: app/database
    ports:
      - 54321:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - go-bootcamp
  app:
    build: app/
    restart: on-failure
    tty: true
    stdin_open: true
    depends_on:
      - db
    env_file:
      - app/.env
    networks:
      - go-bootcamp
    ports:
      - 5050:5050
    volumes:
      - .:/usr/src/app/


volumes:
  postgres_data:

networks:
  go-bootcamp:
    driver: bridge